name: ringcentral
description: RingCentral SDK for Dart language. It allows developers to invoke RingCentral Platform API. You can do a couple of things with this API, like sending SMS, downloading call logs, monitoring your co-workers presence...etc.
version: 0.1.1
homepage: https://github.com/ringcentral/ringcentral-dart

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
